<div id="chart"></div>
<script type="text/javascript">
	var chart = c3.generate({
		bindto: '#chart',
		data: {
			columns: [
				['data1', 3.2, 2.6, 1.4, 4.5, 1.3, 2.8],
			]
		}
	});
</script>
{*
<div id="{$chartId}" style="width: {!$width}; height: {!$height};"></div>

<script type="text/javascript">
	var xs = { };
	var names = { };
	var columns = [];

	{var $i = 0}
	{foreach $series as $serie}
		{? $i++}

		xs['data{!$i}'] = 'x{!$i}';
		names['data{!$i}'] = {$serie->getTitle()};

		var columnX = ['x{!$i}'];
		var columnY = ['data{!$i}'];

		{foreach $serie->getSegments() as $segment}
			columnX.push({$segment->getX()});
			columnY.push({$segment->getY()});
		{/foreach}

		columns.push(columnX);
//		columns.push(columnY);
		//series.push({ color: {$serie->getColor()}, label: {$serie->getTitle()} });

	{/foreach}

	console.log(columns);

	var chart = c3.generate({
		bindto: {$chartId},
		data: {
			xs: {
				'data1': 'x1',
				'data2': 'x2'
			},
			columns: [
				['x1', 10, 30, 45, 50, 70, 100],
				['x2', 30, 50, 75, 100, 120],
				['data1', 30, 200, 100, 400, 150, 250],
				['data2', 20, 180, 240, 100, 190]
			]
		}
	});

	c3.generate({
		bindto: {$chartId},
		data: {
//			xs: xs,
//			names: names,
			columns: columns
		}
	});
</script>
*}