<div id="{$chartId}" style="width: {!$width}; height: {!$height};"></div>

<style type="text/css">
	span.bar-chart-sum{
	    font-size: 12px;
	}
</style>

<script type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.barRenderer.min.js"></script>
<script type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.categoryAxisRenderer.min.js"></script>
<script type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.pointLabels.min.js"></script>
<script type="text/javascript">
//<![CDATA[

	jQuery(document).ready(function() {
		$.jqplot.sprintf.thousandsSeparator = ' ';
		var data = [];
		var serie = null;
		var series = [];
		var ticks = [];
		
		{foreach $series as $serie}
			{var $isFirstSerie = $iterator->isFirst()}
			serie = [];
			
			{foreach $serie->getSegments() as $segment}
				{if $isStacked}
					serie.push({$segment->getValue()});
					
					{if $isFirstSerie}
						ticks.push({$segment->getTitle()});
					{/if}
				{else}
					serie.push([{$segment->getTitle()}, {$segment->getValue()}]);
				{/if}
			{/foreach}
				
			data.push(serie);
			series.push({ label: {$serie->getTitle()} });

		{/foreach}
		
		jQuery.jqplot({$chartId}, data, {
			{if $isStacked}stackSeries: true,{/if}
			seriesDefaults: {
				renderer: jQuery.jqplot.BarRenderer,
				rendererOptions: {
					fillToZero: true
				},
				pointLabels: {
					show: true,
					hideZeros: true,
					escapeHTML: false
				}

			},
			axes: {
				xaxis: {
					{if $isStacked}ticks: ticks,{/if}
					renderer: jQuery.jqplot.CategoryAxisRenderer
				},
				yaxis: {
					tickOptions: {
						formatString: '%i' + {$valueSuffix}
					}
				}
			},
			series: series,
			legend: {
				show: true,
				placement: 'outsideGrid'
			}
		});
	});
//]]>
</script>
