<div id="{$chartId}" style="width: {!$width}; height: {!$height};"></div>

<script type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.highlighter.min.js"></script>
<script type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.dateAxisRenderer.min.js"></script>
<script type="text/javascript">
//<![CDATA[

	jQuery(document).ready(function() {
		$.jqplot.sprintf.thousandsSeparator = ' ';
		var data = [];
		var serie = null;
		var series = [];
		
		{foreach $series as $serie}
			serie = [];
			
			{foreach $serie->getSegments() as $segment}
				serie.push([{$segment->getDateTime()->format('Y-m-d')}, {$segment->getValue()}]);
			{/foreach}
				
			data.push(serie);
			series.push({ color: {$serie->getColor()}, label: {$serie->getTitle()} });
			{? if($serie->getTitle()) $legend = true}
		{/foreach}
		{default $legend => false}
		
		jQuery.jqplot({$chartId}, data, {
			axes: {
				xaxis: {
					renderer: jQuery.jqplot.DateAxisRenderer,
					tickOptions: {
						formatString: '%#d.%#m.%Y'
					}
				},
				yaxis: {
					tickOptions: {
						formatString: '%i' + {$valueSuffix}
					}
				}
			},
			highlighter: {
				show: true,
				sizeAdjust: 7.5
			},
			series: series
			{if $legend}
			,legend: {
				show: true,
				location: 'ne'
			}
			{/if}
		});
	});
//]]>
</script>
