<div id="{$chartId}" style="width: {!$width}; height: {!$height};">
	<div n:if="count($segments) == 0" class="empty-chart-warning">
		nedostatek dat k realizaci grafu...
	</div>
</div>

<script n:if="$type === 'pie'" type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.pieRenderer.min.js"></script>
<script n:if="$type === 'donut'" type="text/javascript" src="{$basePath}/jscripts/jqplot/plugins/jqplot.donutRenderer.min.js"></script>
<script type="text/javascript" n:if="$segments">
//<![CDATA[

	jQuery(document).ready(function() {
		var data = [[]];

		{foreach $segments as $segment}
			data[0].push([{$segment->getTitle()}, {$segment->getValue()}]);
		{/foreach}
		
		jQuery.jqplot({$chartId}, data, {
			seriesDefaults: {
				renderer: {if $type === 'pie'}jQuery.jqplot.PieRenderer{else}jQuery.jqplot.DonutRenderer{/if},
				rendererOptions: {
					{if $type === 'donut'}sliceMargin: 3,{/if}
					startAngle: -90,
					showDataLabels: true,
					dataLabels: {$dataLabelType}
				}
			},
			legend: {
				show: true,
				location: 'e'
			}
		});
	});

//]]>
</script>
